title: Ólafur Hákon Sigurðarson # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently finishing M.Sc. in Economics at Aarhus BSS
  <br><br>
  B.S. in Economics from the University of Iceland.
  <br><br>
  Interested in Quasi-experimental micro methods, time-series modeling as well as being an esports data enthusiast.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  <br><br>
  Contact. olafur.hakon@gmail.com
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
